version: "3.7"

services: 
    go:
        build: 
            context: .
            dockerfile: docker/go/Dockerfile
        ports: 
            - "8080:8080"
        volumes: 
            - ./:/go/src/golang_rest
        depends_on: 
            - mysql
        networks:
            - local
        restart: unless-stopped

    mysql:
        image: mysql
        networks:
            - local
        hostname: mysql
        restart: always
        environment:
            MYSQL_DATABASE: golang_rest
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        ports:
            - '3306:3306'
        volumes:
            - /home/mysql-db:/var/lib/mysql

networks:
    local: