version: "3.7"

services: 
    go:
        build: 
            context: .
            dockerfile: docker/go/Dockerfile
        ports: 
            - "8080:8080"
        volumes: 
            - ./:/go/src/golang_rest
        # restart: unless-stopped